#local:
#  image: wemeep/wemeep-session-service
#  image: sessionservice
#  ports:
#    - "4567:4567"
#  links:
#    - mongo:dbmeep

postgre:
  image: wnameless/postgresql-phppgadmin
  ports:
    - "49161:80"
    - "49160:22"
    - "49162:5432"
  restart: always
  privileged: true
  container_name: dbsession
  volumes:
    - ./sessionData:/data
  environment:
    - PG_USER
    - PG_PASS
  cap_add:
    - SYS_RESOURCE
